export default {
  SAVE_SEGMENT: "SAVE_SEGMENT",
  SEGMENT_SELECTED: "SEGMENT_SELECTED",
  LOAD_SEGMENTS: "LOAD_SEGMENTS",
  DELETE_SEGMENT: "DELETE_SEGMENT",
  NEW_SEGMENT: "NEW_SEGMENT",
  LOAD_POINTS: "LOAD_POINTS"
};
